### PYTHON

In [1]:
print("this is sparta")

this is sparta


In [2]:
a1=10

In [3]:
a1


10

In [5]:
type(a1)

int

In [6]:
a1=3.41

In [8]:
a1

3.41

In [9]:
type(a1)

float

In [12]:
a1="true"

In [14]:
a1

'true'

In [15]:
type(a1)

str

In [24]:
a1 = True

In [25]:
a1

True

In [26]:
type(a1)

bool

In [27]:
a1=3+4j

In [28]:
a1

(3+4j)

In [29]:
type(a1)

complex

#OPERATERS IN PYTHON
1.ARITHMETIC OPERATERS
2.RELATIONAL OPERATERS
3.LOGICAL OPERATERS

# ARITHMETIC OPERATORS
=,-,/,*

In [35]:
a=10
b=20

In [36]:
a,b

(10, 20)

In [37]:
a+b

30

In [38]:
a-b

-10

In [39]:
a*b

200

In [40]:
a/b

0.5

# RELATIONAL OPERATORS
<,>,==,!=

In [42]:
a=50
b=100

In [43]:
a>b

False

In [44]:
a<b

True

In [45]:
a==b

False

In [46]:
a!=b

True

# LOGICAL OPERATORS
 &,|     AND  , OR

In [50]:
a=True
b=False

In [51]:
a&a

True

In [47]:
a&a

50

In [52]:
a&b

False

In [53]:
b&a

False

In [54]:
b&b

False

In [55]:
a|b

True

In [56]:
a|a

True

In [57]:
b|a

True

In [58]:
b|b

False

# python tokens
smallest meaningful component in a program
1. KEY WORD-key words are specially reseved words ex-Fasle,True,del,if

2. IDENTIFIER-are names used for variables, functions or object ex-student= "maths"

3. LITERALS-are constant in python ex-a=3.14
4. OPERATORS

# PYTHON STRINGS
strings are sequence of charecters enclosed within single quotes(''),double quotes("") or tripple quote("''")

In [59]:
str1= 'this is my first string'

In [60]:
str1

'this is my first string'

In [61]:
str2="this is my second string"

In [62]:
str2

'this is my second string'

# EXTRACTING INDIVIDUAL CHARECTERS


In [65]:
my_string="my name is indu"

In [66]:
my_string[0]

'm'

In [67]:
my_string[-1]

'u'

In [69]:
my_string[4]

'a'

In [70]:
my_string[-3]

'n'

In [71]:
my_string[2:8]

' name '

In [72]:
my_string[3:10]

'name is'

# STRING FUNCTIONS

In [ ]:
#FINDING LENGTH OF STRING

In [73]:
len(my_string)

15

In [ ]:
#converting string to lower case

In [74]:
my_string.lower()

'my name is indu'

In [ ]:
#converting string to upper case

In [75]:
my_string.upper()

'MY NAME IS INDU'

In [76]:
my_string="this is sparta"

In [77]:
len(my_string)

14

In [78]:
my_string

'this is sparta'

In [79]:
my_string.upper()

'THIS IS SPARTA'

In [80]:
my_string.lower()

'this is sparta'

In [ ]:
#STRING FUNCTIONS

In [ ]:
#REPLACING SUB STRING

In [81]:
my_string.replace('i','u')

'thus us sparta'

In [83]:
my_string.replace('ar','cv')

'this is spcvta'

In [84]:
new_string="hello madam hello madam hello"

In [85]:
new_string.count("hello")

3

In [86]:
new_string.count('madam')

2

In [ ]:
#FINDING THE INDEX OF SUBSTRINGS

In [90]:
s1="this is indu!!!"

In [95]:
s1.find("indu")

8

In [96]:
s1.find(s1)

0

In [97]:
s1.find('is')

2

In [98]:
s2="this is indu"

In [99]:
s2.find("indu")

8

In [100]:
s2.find("this")

0

In [101]:
fruit='i like apples,mango,banana'

In [102]:
fruit.split(",")

['i like apples', 'mango', 'banana']

In [103]:
my_string="hello world is awesome"

In [105]:
my_string.find('i')

12

In [107]:
str_final="president modi is the best president of india"

In [108]:
str_final.find('i')

4

In [109]:
str_final.find('b')

22

In [110]:
str_final.split('e')

['pr', 'sid', 'nt modi is th', ' b', 'st pr', 'sid', 'nt of india']

In [112]:
str_final.split('d')

['presi', 'ent mo', 'i is the best presi', 'ent of in', 'ia']

# DATA STRUCTURE IN PYTHON
1. TUPPLE
2. LIST
3. DICTIONARY
4. SET

# TUPLE- is an ordered collection of elements enclosed within(), are immutable

In [115]:
tup1=(1,'a',3.14,"indu",True,2-7j)

In [116]:
tup1

(1, 'a', 3.14, 'indu', True, (2-7j))

In [117]:
type(tup1)

tuple

In [ ]:
#EXTRACTING INDIVIDUAL ELEMENT IN TUPLE

In [1]:
tup1=(1,"a",True,2,"b",False)

In [2]:
tup1

(1, 'a', True, 2, 'b', False)

In [3]:
tup1[0]

1

In [4]:
tup1[-1]

False

In [5]:
tup1[1:4]

('a', True, 2)

In [6]:
tup1[0:2]

(1, 'a')

#MODIFYING A TUPLE(IMMUTABLE)

In [7]:
tup1[2]="hello"

TypeError: 'tuple' object does not support item assignment

In [8]:
tup1[2]='this is sparta'

TypeError: 'tuple' object does not support item assignment

In [9]:
tup1

(1, 'a', True, 2, 'b', False)

In [10]:
len(tup1)

6

#CONCATENATING TUPLES

In [12]:
tup1=(1,2,3)

In [13]:
tup2=(4,5,6)

In [14]:
tup1+tup2

(1, 2, 3, 4, 5, 6)

In [15]:
tup1,tup2

((1, 2, 3), (4, 5, 6))

In [16]:
tup2,tup1

((4, 5, 6), (1, 2, 3))

In [17]:
tup2+tup1

(4, 5, 6, 1, 2, 3)

In [18]:
len(tup1)

3

#tuple basic operations-repeating tuple elements

In [20]:
tup1=('indu',2)

In [21]:
tup1*4

('indu', 2, 'indu', 2, 'indu', 2, 'indu', 2)

In [22]:
tup1

('indu', 2)

In [23]:
tup2

(4, 5, 6)

#repeating & concatinating 

In [25]:
tup1*4 + tup2

('indu', 2, 'indu', 2, 'indu', 2, 'indu', 2, 4, 5, 6)

In [26]:
tup1*5

('indu', 2, 'indu', 2, 'indu', 2, 'indu', 2, 'indu', 2)

In [27]:
(tup1*5)*2

('indu',
 2,
 'indu',
 2,
 'indu',
 2,
 'indu',
 2,
 'indu',
 2,
 'indu',
 2,
 'indu',
 2,
 'indu',
 2,
 'indu',
 2,
 'indu',
 2)

In [28]:
tup1*5+tup2

('indu', 2, 'indu', 2, 'indu', 2, 'indu', 2, 'indu', 2, 4, 5, 6)

#tuple functions-minimum value & maximum value

In [30]:
tup1=(1,2,3,4,5,6)

In [31]:
min(tup1)

1

In [32]:
max(tup1)

6

# LIST -its an ordered collection of elemnts are stored in [  ] ,list are mutable

In [33]:
l1=[1,True,False,'a',3j,3.14]

In [34]:
type[l1]

type[[1, True, False, 'a', 3j, 3.14]]

In [35]:
l1

[1, True, False, 'a', 3j, 3.14]

In [36]:
type(l1)

list

#extracting individual elements

In [37]:
l1

[1, True, False, 'a', 3j, 3.14]

In [38]:
l1[2]

False

In [39]:
l1[2:4]

[False, 'a']

In [40]:
l1[-1]

3.14

In [41]:
l2=[1,2,3,3j,'a']

In [42]:
l2

[1, 2, 3, 3j, 'a']

#concatinating

In [43]:
l1,l2

([1, True, False, 'a', 3j, 3.14], [1, 2, 3, 3j, 'a'])

In [44]:
l1+l2

[1, True, False, 'a', 3j, 3.14, 1, 2, 3, 3j, 'a']

In [45]:
l1*2

[1, True, False, 'a', 3j, 3.14, 1, True, False, 'a', 3j, 3.14]

#modifying new element mutable

In [46]:
l1

[1, True, False, 'a', 3j, 3.14]

In [47]:
l2

[1, 2, 3, 3j, 'a']

In [48]:
l1[0]='indu'

In [49]:
l1

['indu', True, False, 'a', 3j, 3.14]

In [51]:
l1[4]='siddapura'

In [52]:
l1

['indu', True, False, 'a', 'siddapura', 3.14]

#appending new element

In [53]:
l1.append("sparta")

In [54]:
l1

['indu', True, False, 'a', 'siddapura', 3.14, 'sparta']

In [56]:
l1.append('renuka')

In [57]:
l1

['indu', True, False, 'a', 'siddapura', 3.14, 'sparta', 'renuka']

#popping last element

In [58]:
l1

['indu', True, False, 'a', 'siddapura', 3.14, 'sparta', 'renuka']

In [59]:
l1.pop()

'renuka'

In [60]:
l1

['indu', True, False, 'a', 'siddapura', 3.14, 'sparta']

In [61]:
l1.pop()

'sparta'

In [62]:
l1

['indu', True, False, 'a', 'siddapura', 3.14]

In [63]:
l1[0]=100

In [64]:
l1

[100, True, False, 'a', 'siddapura', 3.14]

In [67]:
l1.count(100)

1

In [68]:
l1.append(100)

In [69]:
l1

[100, True, False, 'a', 'siddapura', 3.14, 100]

In [70]:
l1.pop()

100

In [71]:
l1

[100, True, False, 'a', 'siddapura', 3.14]

#reversing elements of a list

In [72]:
l1

[100, True, False, 'a', 'siddapura', 3.14]

In [73]:
l1.reverse()

In [74]:
l1

[3.14, 'siddapura', 'a', False, True, 100]

#inserting elements of a list 

In [75]:
l1.insert(1, 'care')

In [76]:
l1

[3.14, 'care', 'siddapura', 'a', False, True, 100]

In [77]:
l1.insert(5,"karnataka")

In [78]:
l1

[3.14, 'care', 'siddapura', 'a', False, 'karnataka', True, 100]

#sorting a list

In [84]:
l1=['apple','orange','banana','mango','guva']

In [85]:
l1

['apple', 'orange', 'banana', 'mango', 'guva']

In [86]:
l1.sort()

In [87]:
l1

['apple', 'banana', 'guva', 'mango', 'orange']

In [88]:
l1.reverse()

In [89]:
l1

['orange', 'mango', 'guva', 'banana', 'apple']

In [91]:
l1.insert(3,'pinaple')

In [92]:
l1

['orange', 'mango', 'guva', 'pinaple', 'banana', 'apple']

In [93]:
l1.sort()

In [94]:
l1

['apple', 'banana', 'guva', 'mango', 'orange', 'pinaple']

# DICTIONARY - is an unordered collection of elements,thery are stored within{}, dictionary is mutable
ex-{"apple":10,"banana":20}
apple, banana --keys
10,20 --values

In [95]:
d1={'apple':50,'mango':20,'guava':30,'banana':500}

In [96]:
d1

{'apple': 50, 'mango': 20, 'guava': 30, 'banana': 500}

In [97]:
type(d1)

dict

#extracting keys and values

In [98]:
d1

{'apple': 50, 'mango': 20, 'guava': 30, 'banana': 500}

In [99]:
d1.keys()

dict_keys(['apple', 'mango', 'guava', 'banana'])

In [100]:
d1.values()

dict_values([50, 20, 30, 500])

#modifying dictionary

In [101]:
d1["mango"]=40

In [102]:
d1

{'apple': 50, 'mango': 40, 'guava': 30, 'banana': 500}

In [103]:
d1['apple']=100

In [104]:
d1

{'apple': 100, 'mango': 40, 'guava': 30, 'banana': 500}

In [105]:
d1['banana']=1

In [106]:
d1

{'apple': 100, 'mango': 40, 'guava': 30, 'banana': 1}

In [107]:
d1['guava']=2

In [108]:
d1

{'apple': 100, 'mango': 40, 'guava': 2, 'banana': 1}

# update one dictionary elements with another

In [1]:
fruit1={'apple':10,'banana':20}

In [2]:
fruit2={"mango":30,"guava":40}

In [3]:
fruit1.update(fruit2)

In [4]:
fruit1

{'apple': 10, 'banana': 20, 'mango': 30, 'guava': 40}

In [6]:
fruit2.update(fruit1)

In [7]:
fruit2

{'mango': 30, 'guava': 40, 'apple': 10, 'banana': 20}

# poping element

In [10]:
fruit1.pop('banana')

20

In [11]:
fruit1

{'apple': 10, 'mango': 30, 'guava': 40}

In [13]:
fruit2.values()

dict_values([30, 40, 10, 20])

In [14]:
fruit2.keys()

dict_keys(['mango', 'guava', 'apple', 'banana'])

# SET IN PYTHON-is an unordered and unindexed collection of elements enclosed within {},dublicates are not allowed in set 

In [21]:
s1={1,2,3,4,'sparta',True,False,1,2,3,4,False}

In [22]:
s1

{1, 2, 3, 4, False, 'sparta'}

# set operations

add elements to dictionary

In [23]:
s1

{1, 2, 3, 4, False, 'sparta'}

In [24]:
s1.add("hello")

In [25]:
s1

{1, 2, 3, 4, False, 'hello', 'sparta'}

In [26]:
s1.add(True)

In [27]:
s1

{1, 2, 3, 4, False, 'hello', 'sparta'}

# updating multiple element

In [28]:
s1

{1, 2, 3, 4, False, 'hello', 'sparta'}

In [35]:
s1.update(['hue',10,3.14])

In [36]:
s1

{1, 10, 2, 3, 3.14, 4, False, 'e', 'h', 'hello', 'hue', 'sparta', 'u'}

In [37]:
s1.remove("h")

In [38]:
s1

{1, 10, 2, 3, 3.14, 4, False, 'e', 'hello', 'hue', 'sparta', 'u'}

In [39]:
s1.add("h")

In [40]:
s1

{1, 10, 2, 3, 3.14, 4, False, 'e', 'h', 'hello', 'hue', 'sparta', 'u'}

In [41]:
s1.update(['here',50])

In [42]:
s1

{1,
 10,
 2,
 3,
 3.14,
 4,
 50,
 False,
 'e',
 'h',
 'hello',
 'here',
 'hue',
 'sparta',
 'u'}

# set function


union of two sets,
inter section of two sets.

In [43]:
s1={1,2,3,4}

In [44]:
s2={'a','b','c'}

In [45]:
s1.union(s2)

{1, 2, 3, 4, 'a', 'b', 'c'}

In [46]:
s1

{1, 2, 3, 4}

In [50]:
s2={2,3,4,5}

In [51]:
s2

{2, 3, 4, 5}

In [52]:
s1.intersection(s2)

{2, 3, 4}

# IF STATEMENT-if ,esle pseudo code

In [59]:
a=10

In [60]:
b=20

In [61]:
if b>a:
    print("b is greater than a")

b is greater than a


In [62]:
if a>b:
     print("a is greater than b")

In [63]:
if a>b:
     print("a is greater than b")
else:
     print("b is greater than a")
        
    

b is greater than a


In [65]:
a=10
b=20
c=30

In [76]:
if (a>b)&(a>c):
     print("a is the greatest")
elif (b>a)&(b>c):
     print("b is the greates")
else: 
    print("c is the greates")
    

c is the greates


#IF WITH TUPLE

In [77]:
tup1=('a',"b","c")

In [78]:
tup1

('a', 'b', 'c')

In [79]:
if "b" in tup1:
     print("b in tup1")

b in tup1


In [80]:
if "z" in tup1:
     print("z in tup1")
else:
     print("z is not in tup1")

z is not in tup1


#if with list

In [81]:
l1=['a','b','c']

In [82]:
l1

['a', 'b', 'c']

In [89]:
if l1[1]=='b':
    l1[1]='z'

In [90]:
l1

['a', 'z', 'c']

In [91]:
if l1[0]=='a':
 l1[0]='x'

In [92]:
l1

['x', 'z', 'c']

#if with dictionary

In [93]:
d1={'k1':10,'k2':20,'k3':30}

In [94]:
d1

{'k1': 10, 'k2': 20, 'k3': 30}

In [97]:
if d1['k3']==30:
     d1['k3']=40

In [98]:
d1

{'k1': 10, 'k2': 20, 'k3': 40}

In [99]:
if d1['k2']==20:
     d1['k2']=d1['k2']+100

In [100]:
d1

{'k1': 10, 'k2': 120, 'k3': 40}

# LOOPING STATEMENTS-are used to repeat a task multiple items.

two types -1. while loop,
           2. for loop.

# WHILE LOOP

In [103]:
i=1
while i<=10:
    print(i)
    i=i+1

1
2
3
4
5
6
7
8
9
10


In [106]:
i=2
while i<=20:
    print(i)
    i=i+ 2

2
4
6
8
10
12
14
16
18
20


In [110]:
i=4
n=20
while i<=20:
    print(i)
    i=i+4

4
8
12
16
20


In [113]:
i=5
n=50
while i
<=50:
    print(i)
    i=i+5

5
10
15
20
25
30
35
40
45
50


In [117]:
i=1
n=2
while i<=20:
     print(n,'*',i,'=',n*i)
     i=i+1   

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20
2 * 11 = 22
2 * 12 = 24
2 * 13 = 26
2 * 14 = 28
2 * 15 = 30
2 * 16 = 32
2 * 17 = 34
2 * 18 = 36
2 * 19 = 38
2 * 20 = 40


In [124]:
i=2
n=2
while i<=20:
    print(n,'*',i,'=',n*i)
    i=i+2  

2 * 2 = 4
2 * 4 = 8
2 * 6 = 12
2 * 8 = 16
2 * 10 = 20
2 * 12 = 24
2 * 14 = 28
2 * 16 = 32
2 * 18 = 36
2 * 20 = 40


# while with list

In [125]:
l1=[1,2,3,4,5]

In [126]:
l1

[1, 2, 3, 4, 5]

In [129]:
i=0
while i<len(l1):
    l1[i]=l1[i]+100
    i=i+1

In [130]:
l1

[101, 102, 103, 104, 105]

In [131]:
l2=[2,4,6,8]

In [132]:
l2

[2, 4, 6, 8]

In [137]:
i=0
while i<len(l2):
    l2[i]=l2[i]+20
    i=i+1

In [138]:
l2

[80, 24, 160, 28]

In [139]:
l3=[1,2,3,4]

In [140]:
i=0
while i<len(l3):
    l3[i]=l3[i]+200
    i=i+1

In [141]:
l3

[201, 202, 203, 204]

# FOR LOOP-is used to iterate over a sequence ( tuple,list,dictionary.....)

In [16]:
l1=['mango','banana','guva','apple']

In [17]:
for i in l1:
    print(i)

mango
banana
guva
apple


In [ ]:
# multiple for loop

In [19]:
l1

['mango', 'banana', 'guva', 'apple']

In [20]:
l2=['chair','book','laptop']

In [21]:
l2

['chair', 'book', 'laptop']

In [22]:
for i in l1:
    for j in l2:
        print(i,j)

mango chair
mango book
mango laptop
banana chair
banana book
banana laptop
guva chair
guva book
guva laptop
apple chair
apple book
apple laptop


# python function- function is a block of code which performs a specific task

In [29]:
def hello():
    print("hello world")
    

In [30]:
hello()

hello world


In [31]:
def add_10(x):
    return x+10

In [32]:
add_10(5)

15

In [33]:
def add_0(x):
    return x+0

In [34]:
add_0(2)

2

In [36]:
def odd_even(x):
    if x%2==0:
        print(x,"is even")
    else: 
            print(x,"is odd")

In [37]:
odd_even(5)

5 is odd


In [38]:
odd_even(20)

20 is even


In [39]:
def sub_2(x):
    return x-2

In [40]:
sub_2(6)

4

In [41]:
def mul_4(x):
    return x*4

In [42]:
mul_4(10)

40

In [43]:
def div_(x):
    return x/2

In [44]:
div_(40)

20.0

# lambda function

In [51]:
g=lambda x: x*x*x

In [52]:
g(2)

8

In [53]:
g(4)

64

In [54]:
g(10)

1000

In [55]:
g(5)

125

In [56]:
g=lambda x:x+x+x

In [57]:
g(2)

6

In [58]:
g(4)

12

In [59]:
g=lambda x:x-x

In [60]:
g(3)

0

In [61]:
g(4)

0

# lambda with filter

In [62]:
l1=[87,56,90,34,2,5,7,1,7,98]

#for odd number

In [64]:
finallist=list(filter(lambda x:(x%2!=0),l1))

In [65]:
finallist

[87, 5, 7, 1, 7]

#for even number

In [67]:
finallist=list(filter(lambda x:(x%2==0),l1))

In [68]:
finallist

[56, 90, 34, 2, 98]

In [69]:
l2=[13,22,44,54,55,78,79,5,7,9,24]

In [72]:
filterlisteven=list(filter(lambda x:(x%2==0),l2))

In [73]:
filterlisteven

[22, 44, 54, 78, 24]

In [81]:
filterlistodd=list(filter(lambda x:(x%2!=0),l2))

In [82]:
filterlistodd

[13, 55, 79, 5, 7, 9]

# lambda with map

In [76]:
l1=[1,2,3,4,5,6,7,8]

In [77]:
list_final_new=list(map(lambda x:x*2,l1))

In [78]:
list_final_new

[2, 4, 6, 8, 10, 12, 14, 16]

In [83]:
l2=[2,4,6,8,10]

In [84]:
maplist=list(map(lambda x:x*2,l2))

In [85]:
maplist

[4, 8, 12, 16, 20]

In [88]:
from functools import reduce

In [91]:
l2

[2, 4, 6, 8, 10]

In [95]:
sum=reduce(lambda x,y:x+y,l2)

In [96]:
sum

30

In [100]:
l1

[1, 2, 3, 4, 5, 6, 7, 8]

In [97]:
sum1=reduce(lambda x,y:x+y,l1)

In [99]:
sum1

36

# python is an object oriented programming language

# greating the first class

In [105]:
class phone:
    def make_call(self):
        print("i am making a call")
    def play_game(self):
        print("i am playing game")

In [106]:
p1=phone()

In [107]:
p1.make_call()

i am making a call


In [108]:
p1.play_game()

i am playing game


In [109]:
class mother:
    def care_family(self):
        print("she cares a whole family")
    def make_cook(self):
        print("she cooks for everyone")

In [111]:
m=mother()

In [112]:
m.care_family()

she cares a whole family


In [114]:
m.make_cook()

she cooks for everyone


In [115]:
class phone:
    def set_color(self,color):
        self.color=color
    def set_cost(self,cost):
        self.cost=cost
    def show_color(self):
        return self.color
    def show_cost(self):
        return self.cost
    def make_call(self):
        print("make a call")
    def play_game(self):
        print("play a game")

In [116]:
p2=phone()

In [117]:
p2.set_color("blue")

In [118]:
p2.set_cost(5000)

In [119]:
p2.show_color()

'blue'

In [120]:
p2.show_cost()

5000

In [121]:
p2.make_call()

make a call


In [122]:
p2.play_game()

play a game


In [124]:
class kurti:
    def set_color(self,color):
        self.color=color
    def set_cost(self,cost):
        self.cost=cost
    def show_color(self):
        return self.color
    def show_cost(self):
        return self.cost
    def make_trail(self):
        print("u can trail kruti")
        

In [125]:
k1=kurti()

In [126]:
k1.set_color("green")

In [127]:
k1.set_cost(250)

In [128]:
k1.show_color()

'green'

In [129]:
k1.show_cost()

250

In [130]:
k1.make_trail()

u can trail kruti


# CREATING A CLASS WITH CONSTRUCTOR-INIT METHOD ACT AS CONSTRUCTOR

In [ ]:
#create constructor

# INHERITANCE -SENGLE INHERITANCE

#parent cass

In [81]:
class employee:
    def __init__(self,name,age,salary,gender):
        self.name=name
        self.age=age
        self.salary=salary
        self.gender=gender
    def show_employee_details(self):
        print("name of the employee is",self.name)
        print("age of the employee is",self.age)
        print("salary of the employee is",self.salary)
        print("gender of the employee is",self.gender)

In [83]:
e1=employee('ram',35,45000,'mail')

In [84]:
e1.show_employee_details()

name of the employee is ram
age of the employee is 35
salary of the employee is 45000
gender of the employee is mail


#child class

In [85]:
class engineer:
    def __init__(self,name,age,doj,salary,gender):
        self.name=name
        self.age=age
        self.doj=doj
        self.salary=salary
        self.gender=gender
    def show_engineer_details(self):
        print("name of engineer is",self.name)
        print("age of engineer is",self.age)
        print("doj of engineer is",self.doj)
        print("salary of engineer is",self.salary)
        print("gender of engineer is",self.gender)

In [86]:
e2=engineer("indira",37,1-1-2024,50000,"femail")

In [87]:
e2.show_engineer_details()

name of engineer is indira
age of engineer is 37
doj of engineer is -2024
salary of engineer is 50000
gender of engineer is femail


# INHERITANCE IN PYTHON

In [155]:
one class can derive the properties of other class

In [156]:
#super class

In [88]:
class vehical:
    def __init__(self,milage,cost):
        self.milage=milage
        self.cost=cost
    def show_vehical_details(self):
        print("milage of car is",self.milage)
        print("cost of car is",self.cost)
        print("i am a vehical")

In [89]:
v1=vehical(400,5000)

In [90]:
v1.show_vehical_details()

milage of car is 400
cost of car is 5000
i am a vehical


#child class

In [91]:
class car(vehical):
    def show_car_details(self):
        print("i am a car")

In [92]:
c1=car(250,800)

In [93]:
c1.show_car_details()

i am a car


In [94]:
c1.show_vehical_details()

milage of car is 250
cost of car is 800
i am a vehical


In [14]:
#super class

In [3]:
class scooter:
    def __init__(self,milage,cost):
        self.milage=milage
        self.cost=cost
    def show_scooter_details(self):
            print("milage of scooter is",self.milage)
            print("cost of scooter is",self.cost)
            print("i am a scooter")

In [4]:
c2= scooter(200,5000)

In [5]:
c2.show_scooter_details()

milage of scooter is 200
cost of scooter is 5000
i am a scooter


#child class

In [6]:
class scooty(scooter):
    def show_scooty_details(self):
        print("i am a scooty")
    

In [7]:
t1=scooty(100,20000)

In [8]:
t1.show_scooty_details()

i am a scooty


In [9]:
t1.show_scooter_details()

milage of scooter is 100
cost of scooter is 20000
i am a scooter


# over riding init method

# here invoking show_details()  method from parent class

invoking show_car_details() method from child class

#parent class

In [24]:
class vehical:
    def __init__(self,milage,cost):
        self.milage=milage
        self.cost=cost
        
    def show_vehical_details(self):
        print("milage of car is",self.milage)
        print("cost of car is",self.cost)
        print("i am a vehical")

In [25]:
v1=vehical(100,40000)

In [26]:
v1.show_vehical_details()

milage of car is 100
cost of car is 40000
i am a vehical


#child lass

In [53]:
class car(vehical):
    def __init__(self,milage,cost,tyres,hp): 
        super().__init__(milage,cost)
        self.tyres=tyres
        self.hp=hp
    
    def show_car_details(self):
        print("number of tyres in a car:",self.tyres)
        print("hourse per hour of car is",self.hp)
        print("i am a car")

In [54]:
c1=car(200,50000,8,999)

In [55]:
c1.show_car_details()

number of tyres in a car: 8
hourse per hour of car is 999
i am a car


In [57]:
c1.show_vehical_details()

milage of car is 200
cost of car is 50000
i am a vehical


#parent class

In [68]:
class cloth:
    def __init__(self,color,cost):
        self.color=color
        self.cost=cost
    def show_cloth_details(self):
        print("color of a cloth is",self.color)
        print("cost of a cloth is",self.cost)
        print("i am a cloth")

In [69]:
c1=cloth("green",250)

In [70]:
c1.show_cloth_details()

color of a cloth is green
cost of a cloth is 250
i am a cloth


#child class

In [77]:
class kurti(cloth):
    def __init__(self,color,cost,pattern,neck):
        super().__init__(color,cost)
        self.pattern=pattern
        self.neck=neck
    def show_kurti_details(self):
        print("pattern of kurti ",self.pattern)
        print("neck of kurti",self.neck)
        print("i am a kurti")

In [78]:
k1=kurti("green",200,"umbrella","round")

In [79]:
k1.show_cloth_details()

color of a cloth is green
cost of a cloth is 200
i am a cloth


In [80]:
k1.show_kurti_details()

pattern of kurti  umbrella
neck of kurti round
i am a kurti


# TYPES OF INHERITANCE 
1.SINGLE INHERITANCE
2.MULTIPLE INHERITANCE
3.MULTI_LEVEL INHERITANCE
4.HYBRID INHERITANCE

# MULTIPLE INHERITANCE

#parent1

In [32]:
class parent1:
    def assign_string_one(self,str1):
        self.str1=str1
    
    def show_string_one(self):
        return self.str1

#parent2

In [33]:
class parent2:
    def assign_string_two(self,str2):
        self.str2=str2
        
    def show_string_two(self):
        return self.str2

#child

In [35]:
class child(parent1,parent2):
    def assign_string_three(self,str3):
        self.str3=str3
        
    def show_string_three(self):
        return self.str3

In [36]:
my_child=child()

In [37]:
my_child.assign_string_one("am str of parent one")

In [38]:
my_child.assign_string_two("am str of parent two")

In [39]:
my_child.assign_string_three("am str of child")

In [40]:
my_child.show_string_one()

'am str of parent one'

In [41]:
my_child.show_string_two()

'am str of parent two'

In [42]:
my_child.show_string_three()

'am str of child'

#PARENT1

In [43]:
class part1:
    def assign_string1(self,str1):
        self.str1=str1
    def show_string1(self):
        return self.str1

In [44]:
class part2:
    def assign_string2(self,str2):
        self.str2=str2
    def show_string2(self):
        return self.str2

In [46]:
class child(part1,part2):
    def assign_string3(self,str3):
        self.str3=str3
    def show_string3(self):
        return self.str3

In [47]:
part4=child()

In [49]:
part4.assign_string1("am str1")

In [50]:
part4.assign_string2("am str2")

In [51]:
part4.assign_string3("am str3")

In [52]:
part4.show_string1()

'am str1'

In [53]:
part4.show_string2()

'am str2'

In [54]:
part4.show_string3()

'am str3'

#MULTI LEVEL INHERITANCE-in this method we have parent-child-grand.child relationship

In [55]:
class parent:
    def get_name(self,name):
        self.name=name
    def show_name(self):
        return self.name

In [57]:
class child(parent):
    def get_age(self,age):
        self.age=age
    def show_age(self):
        return self.age

In [62]:
class grandchild(child):
    def get_gender(self,gender):
        self.gender=gender
    def show_gender(self):
        return self.gender

In [63]:
gc=grandchild()

In [64]:
gc.get_name('avinash')

In [65]:
gc.get_age(34)

In [66]:
gc.get_gender('male')

In [67]:
gc.show_name()

'avinash'

In [68]:
gc.show_age()

34

In [69]:
gc.show_gender()

'male'

In [70]:
class part1:
    def get_name(self,name):
        self.name=name
    def show_name(self):
        return self.name

In [72]:
class part2(part1):
    def get_age(self,age):
        self.age=age
    def show_age(self):
        return self.age

In [73]:
class part3(part2):
    def get_gender(self,gender):
        self.gender=gender
    def show_gender(self):
        return self.gender

In [76]:
ml=part3()

In [77]:
ml.get_name('indu')

In [78]:
ml.get_age(37)

In [79]:
ml.get_gender('femail')

In [80]:
ml.show_name()

'indu'

In [81]:
ml.show_age()

37

In [82]:
ml.show_gender()

'femail'

# LIBRARIES IN PYTHON-

# its a collection of functions and methods that allows you to perform many actions without writing your code

# NUMPY
# PANDAS
# MATPLOTLIB

# numpy-
stands for numerical python and is the core library for numeric and scientific computing
        it consists of multi-dimensional array objects and a collection of routines for processing those arrays 

single_dimensional array-[10,20,30,40]
      multi_dimensional array-[[1,2,3,4],[10,30,50,80]]

# pandas 

stands for panel data and is the core library for data manipulation and data analysis 

it consists of single dimensional and multi-dimensional data structures for data manipulation

#single-dimensional->series object
#multi-dimensional->data-frame

#series object is one-dimensional labeled array

# matplotlib

is a python library used for data visualization

you can create bar-plot,scatter-plot,histograms and a lot more with matplotlib

In [3]:
import numpy as np

In [4]:
l1=[1,2,3,4]

In [5]:
n1=np.array(l1)

In [6]:
n1

array([1, 2, 3, 4])

In [7]:
type(n1)

numpy.ndarray

In [8]:
l4=[2,4,6,8]

In [9]:
n4=np.array(l4)

In [10]:
n4

array([2, 4, 6, 8])

In [11]:
type(n4)

numpy.ndarray

In [12]:
n2=np.array([[1,2,3,4],[5,6,7,8]])

In [13]:
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
type(n2)

numpy.ndarray

In [16]:
n3=np.array([['a','b','c','d'],['e','f','h','i']])

In [17]:
n3

array([['a', 'b', 'c', 'd'],
       ['e', 'f', 'h', 'i']], dtype='<U1')

In [18]:
type(n3)

numpy.ndarray

#INITIALIZING NUMPY ARRAY

In [19]:
n5=np.zeros((2,4))

In [20]:
n5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
type(n5)

numpy.ndarray

In [24]:
n6=np.ones((5,8))

In [25]:
n6

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
type(n6)

numpy.ndarray

#INITIALIZING NUMPY ARRAY WITH SAME NUMBER

In [27]:
n7=np.full((3,5),55)

In [28]:
n7

array([[55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55]])

In [29]:
type(n7)

numpy.ndarray

In [30]:
n8=np.full((4,6),25)

In [31]:
n8

array([[25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])

#INTIALIZING NUMPY ARRAY WITHIN A RANGE

In [36]:
import numpy as np

In [40]:
n1=np.arange(50,100)

In [41]:
n1

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [42]:
n2=np.arange(10,20)

In [43]:
n2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [44]:
n1=np.arange(10,45,8)

In [45]:
n1

array([10, 18, 26, 34, 42])

In [48]:
n1=np.arange(20,80,10)

In [49]:
n1

array([20, 30, 40, 50, 60, 70])

#INTITIALLIZING NUMPY ARRAY WITH RANDOM NUMBERS

In [50]:
n2=np.random.randint(100,200,10)

In [51]:
n2

array([110, 163, 108, 102, 105, 191, 143, 156, 136, 128])

In [52]:
n3=np.random.randint(200,300,5)

In [53]:
n3

array([226, 200, 218, 220, 229])

#NUMPY SHAPE

CHECKING THE SHAPE OF NUMPY ARRAY

In [55]:
import numpy as np

In [57]:
n1=np.array([[1,2,3,4],[3,4,5,6]])

In [58]:
n1

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

#shape

In [60]:
n1.shape=(4,2)

In [61]:
n1

array([[1, 2],
       [3, 4],
       [3, 4],
       [5, 6]])

In [62]:
n2=np.array([['a','c','d','e'],[1,2,3,4]])

In [63]:
n2

array([['a', 'c', 'd', 'e'],
       ['1', '2', '3', '4']], dtype='<U11')

In [65]:
n2.shape=(2,4)

In [66]:
n2

array([['a', 'c', 'd', 'e'],
       ['1', '2', '3', '4']], dtype='<U11')

In [67]:
n2.shape=(4,2)

In [68]:
n2

array([['a', 'c'],
       ['d', 'e'],
       ['1', '2'],
       ['3', '4']], dtype='<U11')

In [69]:
n2.shape=(8,1)

In [70]:
n2

array([['a'],
       ['c'],
       ['d'],
       ['e'],
       ['1'],
       ['2'],
       ['3'],
       ['4']], dtype='<U11')

# JOINING NUMPY ARRAY

V STACK()->vertical joining

H STACK()->horizontal joining

COLOUMN_STACK()->column joining

In [72]:
import numpy as np

In [73]:
n1=np.array([1,2,3,4])

In [75]:
n2=np.array([5,6,7,8])

In [76]:
np.vstack((n1,n2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [77]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
np.column_stack((n1,n2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [80]:
n1=[9,8,7]

In [81]:
n2=[4,5,6]

In [82]:
np.vstack((n1,n2))

array([[9, 8, 7],
       [4, 5, 6]])

In [83]:
np.hstack((n1,n2))

array([9, 8, 7, 4, 5, 6])

In [84]:
np.column_stack((n1,n2))

array([[9, 4],
       [8, 5],
       [7, 6]])

# NUMPY INTERSECTION & DIFFERENCE

In [85]:
import numpy as np

In [86]:
n1=np.array([10,20,30,40,50,60])

In [87]:
n2=np.array([50,60,70,80,90])

In [89]:
np.intersect1d(n1,n2)

array([50, 60])

In [90]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [91]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [92]:
n3=[1,2,3,4,5]

In [93]:
n4=[4,5,6,7,8]

In [94]:
np.intersect1d(n1,n2)

array([50, 60])

In [95]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [96]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

# NUMPY ARRAY MATHEMATICS

addition of numpy arrays-sum

In [98]:
n1=np.array([10,20])

In [99]:
n2=np.array([30,40])

In [100]:
np.sum((n1,n2))

100

In [101]:
np.sum((n1,n2),axis=0)

array([40, 60])

In [102]:
np.sum((n1,n2),axis=1)

array([30, 70])

In [103]:
n3=[2,4]

In [104]:
n4=[5,6]

In [106]:
np.sum((n3,n4))

17

In [107]:
np.sum((n3,n4),axis=0)

array([ 7, 10])

In [108]:
np.sum((n3,n4),axis=1)

array([ 6, 11])

# NUMPY ARRAY MATHMETICS

BASIC ADDITION-NS=N1+5
BASIC SUBSTRACTION-NS=N1-5
BASIC MULTIPLICATION-NS=N1*5
BASIC DIVIS0N-NS=N/5

In [109]:
import numpy as np

In [114]:
n1=np.array([10,20,30,40,50])

In [115]:
n1

array([10, 20, 30, 40, 50])

In [116]:
na=n1+5

In [117]:
na

array([15, 25, 35, 45, 55])

In [118]:
ns=n1-5

In [119]:
ns

array([ 5, 15, 25, 35, 45])

In [120]:
nm=n1*5

In [121]:
nm

array([ 50, 100, 150, 200, 250])

In [122]:
nd=n1/5

In [123]:
nd

array([ 2.,  4.,  6.,  8., 10.])

In [124]:
n2=np.array([100,200,300,400,500])

In [125]:
n2

array([100, 200, 300, 400, 500])

In [126]:
na=n2+10

In [127]:
na

array([110, 210, 310, 410, 510])

In [128]:
ns=n2-10

In [129]:
ns

array([ 90, 190, 290, 390, 490])

In [130]:
nm=n2*10

In [131]:
nm

array([1000, 2000, 3000, 4000, 5000])

In [132]:
nd=n2/10

In [133]:
nd

array([10., 20., 30., 40., 50.])

# NUMPY MATH FUNCTION--MEAN....MEDIAN....STANDARD DEVIATION

In [3]:
import numpy as np

In [4]:
n1=np.random.randint(1,40,10)

In [5]:
n1

array([15, 26,  2, 28, 31, 17, 39,  7, 20, 39])

In [6]:
np.median(n1)

23.0

In [7]:
np.mean(n1)

22.4

In [8]:
np.std(n1)

11.884443613396463

# NUMPY SAVE AND LOAD

In [12]:
import numpy as np

In [13]:
n1

array([15, 26,  2, 28, 31, 17, 39,  7, 20, 39])

In [20]:
np.save('myarray',n1)

In [23]:
n2=np.load('myarray.npy')

In [24]:
n2

array([15, 26,  2, 28, 31, 17, 39,  7, 20, 39])

In [25]:
n2

array([15, 26,  2, 28, 31, 17, 39,  7, 20, 39])

In [26]:
np.save('myarray',n2)

In [27]:
n3=np.load('myarray.npy')

In [28]:
n3

array([15, 26,  2, 28, 31, 17, 39,  7, 20, 39])

# python pandas -in series you have to use S in capital

In [2]:
import pandas as pd

In [11]:
s1=pd.Series([1,2,3,4,5])

In [12]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [13]:
type(s1)

pandas.core.series.Series

In [14]:
s2=pd.Series([5,6,7,8,9])

In [15]:
s2

0    5
1    6
2    7
3    8
4    9
dtype: int64

In [16]:
type(s2)

pandas.core.series.Series

#CHANGING INDEX 

In [21]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [22]:
s1=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [23]:
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [24]:
s2

0    5
1    6
2    7
3    8
4    9
dtype: int64

s2=pd.Series([5,6,7,8,9],index=[1,2,3,4,5])

In [26]:
s2

1    5
2    6
3    7
4    8
5    9
dtype: int64

#SERIES OBJECT FROM DICTIONARY

YOU CAN ALSO CREATE A SERIES OBJECT FROM A DICTIONARY

In [27]:
import pandas as pd

In [29]:
pd.Series({'k1':10,'k2':20,'k3':30})

k1    10
k2    20
k3    30
dtype: int64

#changing index position-you can change index position

In [30]:
s5=pd.Series({'k1':10,'k2':20,'k3':30,'k4':40},index=['k4','k2','k3','k1'])

s5

In [32]:
s4=pd.Series({'k2':40,'k8':20,'k3':10,'k1':25},index=['a','b','c','d'])

In [33]:
s4

a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64

In [34]:
s4=pd.Series({'k2':40,'k8':20,'k3':10,'k1':25},index=['k1','k3','k2','k8'])

In [35]:
s4

k1    25
k3    10
k2    40
k8    20
dtype: int64

#EXTRACTING A INDIVIDUAL ELEMENT

#extracting a single element-s1[3]

#extracting a sequence of element-s1[:4]

#etracting a element from a back-s1[-3:]

In [37]:
l1=[1,2,3,4,5,6,7,8,9]

In [38]:
s1=pd.Series(l1)

In [39]:
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [40]:
s1[4]

5

In [41]:
s1[0:4]

0    1
1    2
2    3
3    4
dtype: int64

In [42]:
s1[-4:-1]

5    6
6    7
7    8
dtype: int64

In [43]:
l2=[9,8,7,6,5,4,3,2]

In [44]:
s2=pd.Series(l2)

In [45]:
s2

0    9
1    8
2    7
3    6
4    5
5    4
6    3
7    2
dtype: int64

In [46]:
s2[5]

4

In [47]:
s2[4:7]

4    5
5    4
6    3
dtype: int64

In [48]:
s2[-6:-2]

2    7
3    6
4    5
5    4
dtype: int64

# basic math operation on series

#adding scalar value to series element-s1+10

#adding two series object-s1+s2

#s1*5,......s1/5

In [50]:
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [53]:
s1a=s1+10

In [54]:
s1a

0    11
1    12
2    13
3    14
4    15
5    16
6    17
7    18
8    19
dtype: int64

In [55]:
s1s=s1*10

In [56]:
s1s

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int64

In [57]:
s1d=s1/2

In [58]:
s1d

0    0.5
1    1.0
2    1.5
3    2.0
4    2.5
5    3.0
6    3.5
7    4.0
8    4.5
dtype: float64

In [59]:
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [60]:
s2

0    9
1    8
2    7
3    6
4    5
5    4
6    3
7    2
dtype: int64

In [61]:
add_two_series=s1+s2

In [62]:
add_two_series

0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
5    10.0
6    10.0
7    10.0
8     NaN
dtype: float64

In [63]:
s4

k1    25
k3    10
k2    40
k8    20
dtype: int64

In [64]:
s5

k4    40
k2    20
k3    30
k1    10
dtype: int64

In [65]:
sa=s4+s5

In [66]:
sa

k1    35.0
k2    60.0
k3    40.0
k4     NaN
k8     NaN
dtype: float64

In [67]:
s4+s5

k1    35.0
k2    60.0
k3    40.0
k4     NaN
k8     NaN
dtype: float64

In [68]:
s4*4

k1    100
k3     40
k2    160
k8     80
dtype: int64

In [69]:
s4/2

k1    12.5
k3     5.0
k2    20.0
k8    10.0
dtype: float64

# PYTHON DATA FRAME

#dataframe is a 2-dimensional labelled data_structure

#dtata frame comprises of rows and columns,this is how you can create a data frame

In [1]:
import pandas as pd

In [3]:
pd.DataFrame({'name':['anni','bob','sam'],'marks':[755,85,65]})

name  marks
0  anni    755
1   bob     85
2   sam     65

In [4]:
pd.DataFrame({'name':['ax','bx','cx','dx'],'points':[12,23,45,55]})

name  points
0   ax      12
1   bx      23
2   cx      45
3   dx      55

# DataFrame in built functions

head()--->for first five rows

shape()---->for number of rows n coloumns in data set

describe()---->for general information

tail()---->for last five rows

In [2]:
import pandas as pd

In [3]:
iris=pd.read_csv('iris.csv')

In [4]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [8]:
iris.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [6]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
iris.shape

(150, 5)

In [8]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
iris.iloc[0:3,0:2]

sepal_length  sepal_width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2

In [10]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
iris.min()

sepal_length       4.3
sepal_width        2.0
petal_length       1.0
petal_width        0.1
species         setosa
dtype: object

In [13]:
iris1=iris.iloc[99:127,2:4]

In [14]:
iris1

petal_length  petal_width
99            4.1          1.3
100           6.0          2.5
101           5.1          1.9
102           5.9          2.1
103           5.6          1.8
104           5.8          2.2
105           6.6          2.1
106           4.5          1.7
107           6.3          1.8
108           5.8          1.8
109           6.1          2.5
110           5.1          2.0
111           5.3          1.9
112           5.5          2.1
113           5.0          2.0
114           5.1          2.4
115           5.3          2.3
116           5.5          1.8
117           6.7          2.2
118           6.9          2.3
119           5.0          1.5
120           5.7          2.3
121           4.9          2.0
122           6.7          2.0
123           4.9          1.8
124           5.7          2.1
125           6.0          1.8
126           4.8          1.8

extract specific coloums

In [17]:
iris2=iris.iloc[10:21,[0,4]]

In [18]:
iris2

sepal_length species
10           5.4  setosa
11           4.8  setosa
12           4.8  setosa
13           4.3  setosa
14           5.8  setosa
15           5.7  setosa
16           5.4  setosa
17           5.1  setosa
18           5.7  setosa
19           5.1  setosa
20           5.4  setosa

In [19]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [20]:
iris3=iris.loc[22:33,('petal_width','species')]

In [21]:
iris3

petal_width species
22          0.2  setosa
23          0.5  setosa
24          0.2  setosa
25          0.2  setosa
26          0.4  setosa
27          0.2  setosa
28          0.2  setosa
29          0.2  setosa
30          0.2  setosa
31          0.4  setosa
32          0.1  setosa
33          0.2  setosa

if i want those records only sepal length is greater than 5
>5

#for all records for greater and smaller

In [22]:
iris['sepal_length']>5

0       True
1      False
2      False
3      False
4      False
       ...  
145     True
146     True
147     True
148     True
149     True
Name: sepal_length, Length: 150, dtype: bool

#only for true conditionp

In [24]:
iris[iris['sepal_length']>5]

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
10            5.4          3.7           1.5          0.2     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[118 rows x 5 columns]

#petal_length>2 &species virginica

In [39]:
iris_final= iris[iris['petal_width']>2]

In [51]:
iris_final.head()

sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
102           7.1          3.0           5.9          2.1  virginica
104           6.5          3.0           5.8          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica
109           7.2          3.6           6.1          2.5  virginica

In [15]:
iris5=iris[(iris['petal_length']>2)&(iris['species']=='virginica')]

In [16]:
iris5

sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
101           5.8          2.7           5.1          1.9  virginica
102           7.1          3.0           5.9          2.1  virginica
103           6.3          2.9           5.6          1.8  virginica
104           6.5          3.0           5.8          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica
106           4.9          2.5           4.5          1.7  virginica
107           7.3          2.9           6.3          1.8  virginica
108           6.7          2.5           5.8          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
110           6.5          3.2           5.1          2.0  virginica
111           6.4          2.7           5.3          1.9  virginica
112           6.8          3.0           5.5          2.1  virginica
113           5.7          2.5           5.0          2.0  virginica
114           5.8          2.8           5.1          2.4  virginica
115           6.4          3.2           5.3          2.3  virginica
116           6.5          3.0           5.5          1.8  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
119           6.0          2.2           5.0          1.5  virginica
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [17]:
iris5.head()

sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
101           5.8          2.7           5.1          1.9  virginica
102           7.1          3.0           5.9          2.1  virginica
103           6.3          2.9           5.6          1.8  virginica
104           6.5          3.0           5.8          2.2  virginica

In [18]:
iris5.shape

(50, 5)

In [19]:
iris5.describe()

sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000     50.00000
mean        6.58800     2.974000      5.552000      2.02600
std         0.63588     0.322497      0.551895      0.27465
min         4.90000     2.200000      4.500000      1.40000
25%         6.22500     2.800000      5.100000      1.80000
50%         6.50000     3.000000      5.550000      2.00000
75%         6.90000     3.175000      5.875000      2.30000
max         7.90000     3.800000      6.900000      2.50000

In [20]:
iris5.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [5]:
iris_random=iris[(iris['sepal_length']>6)&(iris['sepal_width']>3)&(iris['petal_length']>6)]

In [21]:
iris_random.head()

sepal_length  sepal_width  petal_length  petal_width    species
109           7.2          3.6           6.1          2.5  virginica
117           7.7          3.8           6.7          2.2  virginica
131           7.9          3.8           6.4          2.0  virginica

In [24]:
iris6=iris[(iris['sepal_length']>4)&(iris['species']=='setosa')]

In [25]:
iris6

sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.1  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.1           1.5          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [26]:
iris6.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [27]:
iris.min()

sepal_length       4.3
sepal_width        2.0
petal_length       1.0
petal_width        0.1
species         setosa
dtype: object

In [28]:
iris.max()

sepal_length          7.9
sepal_width           4.4
petal_length          6.9
petal_width           2.5
species         virginica
dtype: object

In [29]:
iris.mean()

C:\Users\HomePC\AppData\Local\Temp\ipykernel_13760\935066809.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  iris.mean()


sepal_length    5.843333
sepal_width     3.054000
petal_length    3.758667
petal_width     1.198667
dtype: float64

In [30]:
iris.median()

C:\Users\HomePC\AppData\Local\Temp\ipykernel_13760\1297003277.py:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  iris.median()


sepal_length    5.80
sepal_width     3.00
petal_length    4.35
petal_width     1.30
dtype: float64

In [31]:
iris.std()

C:\Users\HomePC\AppData\Local\Temp\ipykernel_13760\3849825860.py:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  iris.std()


sepal_length    0.828066
sepal_width     0.433594
petal_length    1.764420
petal_width     0.763161
dtype: float64